### ISSUE TITLE
Player Sprite Flickers Entering/Leaving Targeting Mode

### ISSUE THREAD

**Issue by Snayff** [Snayff/notquiteparadise#240]
## The Bug
When Targeting Mode is entered/Left (not sure which) the player sprite flickers or moves position. This only appears to happen when the Targeting Mode is triggered in quick succession. 

## Reproduction Instructions
Detail the steps to reproduce the bug. 

1. Press a skill key for a skill that cannot target an open tile.
2. Click on an open tile. 
3. Repeat quickly.

## Expected behaviour
Sprite would not change. 

## Screenshots
![NbDZUlqYKN](https://user-images.githubusercontent.com/23128268/104094286-da368200-5287-11eb-9509-e5d1ff3bddd5.gif)

## Platform
 - OS: Windows 10
 - Python Version: 3.8
 - NQP Version: 0.144.0

## Log Output/Stack Trace
N/A

**Comment by DaFluffyPotato** [comment]
Is that not an animation for attacking or something?

**Comment by Snayff** [comment]
If that is the case it is inconsistently firing and is triggering without the skill actually being used. Not sure what is causing it, tbh. Does the Targeting Mode use the Aesthetic system to draw? I think that's the only place the entity sprites are handled.

**Comment by DaFluffyPotato** [comment]
The targeting mode wasn't complete with that commit. It allowed you to cast to any "valid tile", which was just non-walls. With the new target and cast tags system, the casting works properly now. If you exit the targeting mode with backspace, the "animation" (or whatever it is) doesn't play.

I'm closing this issue since it appears to have only been an issue because the targeting functionality wasn't done yet. Feel free to open it if you think there's actually something wrong.
